name: Deploy AKS and Kubernetes Resources

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{ 
          "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
          "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
          "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
          "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
        }'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
      working-directory: ./terraform

    - name: Configure kubectl
      run: |
        echo "${{ steps.terraform.outputs.kube_config }}" > $HOME/.kube/config
      id: terraform
      working-directory: ./terraform

    - name: Create Kubernetes namespace
      run: kubectl create namespace sock-shop || echo "Namespace already exists"

    - name: Apply Kubernetes manifests
      run: kubectl apply -f complete-demo.yaml
      working-directory: ./deploy/kubernetes

    - name: Set up Azure Monitor for AKS
      run: |
        az aks enable-addons --resource-group aks-resource-group --name aks-cluster --addons monitoring
        az monitor log-analytics workspace create --resource-group aks-resource-group --workspace-name aks-monitor